/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BDothtmlRouteImport } from './routes/B[.]html'
import { Route as KmtRouteImport } from './routes/kmt'
import { Route as SectionARouteImport } from './routes/section-a'
import { Route as WiredRouteImport } from './routes/wired'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BDothtmlRoute = BDothtmlRouteImport.update({
  id: '/B.html',
  path: '/B.html',
  getParentRoute: () => rootRouteImport,
} as any)
const KmtRoute = KmtRouteImport.update({
  id: '/kmt',
  path: '/kmt',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionARoute = SectionARouteImport.update({
  id: '/section-a',
  path: '/section-a',
  getParentRoute: () => rootRouteImport,
} as any)
const WiredRoute = WiredRouteImport.update({
  id: '/wired',
  path: '/wired',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/B.html': typeof BDothtmlRoute
  '/kmt': typeof KmtRoute
  '/section-a': typeof SectionARoute
  '/wired': typeof WiredRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/B.html': typeof BDothtmlRoute
  '/kmt': typeof KmtRoute
  '/section-a': typeof SectionARoute
  '/wired': typeof WiredRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/B.html': typeof BDothtmlRoute
  '/kmt': typeof KmtRoute
  '/section-a': typeof SectionARoute
  '/wired': typeof WiredRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/B.html' | '/kmt' | '/section-a' | '/wired'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/B.html' | '/kmt' | '/section-a' | '/wired'
  id: '__root__' | '/' | '/B.html' | '/kmt' | '/section-a' | '/wired'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BDothtmlRoute: typeof BDothtmlRoute
  KmtRoute: typeof KmtRoute
  SectionARoute: typeof SectionARoute
  WiredRoute: typeof WiredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/B.html': {
      id: '/B.html'
      path: '/B.html'
      fullPath: '/B.html'
      preLoaderRoute: typeof BDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kmt': {
      id: '/kmt'
      path: '/kmt'
      fullPath: '/kmt'
      preLoaderRoute: typeof KmtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section-a': {
      id: '/section-a'
      path: '/section-a'
      fullPath: '/section-a'
      preLoaderRoute: typeof SectionARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wired': {
      id: '/wired'
      path: '/wired'
      fullPath: '/wired'
      preLoaderRoute: typeof WiredRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BDothtmlRoute: BDothtmlRoute,
  KmtRoute: KmtRoute,
  SectionARoute: SectionARoute,
  WiredRoute: WiredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
